import SearchHeader from "./component/SearchHeader";
import SearchSideBar from "./component/SearchSideBar";
import SearchRestaurantCard from "./component/SearchRestaurantCard";
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
export const metadata = {
    title: "Search - Shopeer Food",
    description: "Generated by create next app",
};

export default async function Search(props) {
    const searchKey = Object.values(props.searchParams)[0].toLowerCase();
    const result = await fetchRestaurant(searchKey)
    const location = await fetchLocation()
    const cuisine = await fetchCuisine()
    console.log(props.searchParams)
    return (
        <>
            <SearchHeader></SearchHeader>
            <div className="flex py-4 m-auto w-2/3 justify-between items-start ">
                <SearchSideBar location={location}
                    cuisine={cuisine}
                >
                </SearchSideBar>
                <div className="w-5/6">
                    {result.length > 0 ? result.map((data) => {
                        return <SearchRestaurantCard data={data}></SearchRestaurantCard>
                    }) : <div className="p-32">No Restaurant Found</div>}
                </div>
            </div>
        </>
    )
};

async function fetchRestaurant(searchParams) {
    const where = {}
    if (searchParams.city) {
        const location = {
            name: {
                equals: searchParams.city.toLowerCase()
            }
        }
        where.location = location
    }
    if (searchParams.cuisine) {
        const cuisine = {
            name: {
                equals: searchParams.cuisine.toLowerCase()
            }
        }
    }
    if (searchParams.price) {
        const price = {
            equals: searchParams.price
        }
    }

    const restaurant = await prisma.restaurant.findMany({
        where,
        select: {
            id: true,
            name: true,
            images: true,
            main_image: true,
            price: true,
            cuisine: true,
            location: true,
            slug: true

        }
    })
    return restaurant
}
async function fetchLocation(keyword) {
    return await prisma.location.findMany()
}
async function fetchCuisine(keyword) {
    return await prisma.cuisine.findMany()
}
