
import ReservationHeader from "./components/ReservationHeader";
import ReservationForm from "./components/ReservationForm";

export const metadata = {
    icons: {
        icon: '/icon.ico'
    },
    title: "Reserve at Milestones Grill (Toronto) - Shopeer Food",
    description: "Generated by create next app",
};
export default function Reserve() {
    return (
        <div className="border-t h-screen">
            <div className="py-9 w-3/5 m-auto">
                <ReservationHeader></ReservationHeader>
                <ReservationForm></ReservationForm>
            </div>
        </div>
    )
};
