import Header from "./components/Header";
import RestaurantCard from "./components/RestaurantCard";
import { PrismaClient, Cuisine, Location, PRICE } from "@prisma/client";
export const metadata = {
    icons: {
        icon: '/icon.ico'
    },
    title: "Shopeer Food",
    description: "Generated by create next app",
};
const prisma = new PrismaClient()
const fetchRestaurants = async () => {
    const restaurants = await prisma.restaurant.findMany({
        select: {
            id: true,
            name: true,
            main_image: true,
            cuisine: true,
            location: true,
            price: true,
            slug: true,
            reviews: true,
        }
    })
    return restaurants
}
export default async function Home() {
    const restaurant = await fetchRestaurants();
    return (
        <div className="">
            <Header></Header>
            <div className="py-3 px-36 mt-10 flex flex-wrap justify-center min-w-[640px]">
                {restaurant.map((restaurant) => {
                    return <RestaurantCard restaurant={restaurant}></RestaurantCard>
                })}
            </div>
        </div>
    );
}
