
import RestaurantNavbar from "./component/RestaurantNavbar";
import Title from "./component/Title";
import Rating from "./component/Rating";
import Images from "./component/Images";
import Description from "./component/Description";
import Reviews from "./component/Reviews";
import ReservationCard from "./component/ReservationCard";
import RestaurantHeader from "./component/RestaurantHeader";
import { PrismaClient } from "@prisma/client";
export const metadata = {
    icons: {
        icon: '/icon.ico'
    },
    title: "Shopeer Food",
    description: "Generated by create next app",
};
// export async function getStaticProps() {
//     return { props: { slug: 'HomePage' } }
// }
const prisma = new PrismaClient()
const fetchRestaurants = async (slug) => {
    const restaurant = await prisma.restaurant.findUnique({
        where: {
            slug
        }
    })
    return restaurant;
}
export default async function RestaurantDetails(props) {
    const restaurant = await fetchRestaurants(props.params.slug)

    return (
        <>
            <RestaurantHeader data={restaurant.name}></RestaurantHeader>
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                <div className="bg-white w-[70%] rounded p-3 shadow">
                    <RestaurantNavbar params={restaurant} ></RestaurantNavbar>
                    <Title data={restaurant.name}></Title>
                    <Rating></Rating>
                    <Description data={restaurant.description}></Description>
                    <Images data={restaurant.images} className="hover:scale-110 transition-all"></Images>
                    <Reviews></Reviews>
                </div>
                <div className="w-[27%] relative text-reg">
                    <ReservationCard></ReservationCard>
                </div>
            </div>
        </>
    )
};